### ISSUE TITLE
Restoring content works, but with error message

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-webpages#29]
@kultsar commented on [Thu Sep 27 2018](https://github.com/SenseNet/sensenet/issues/481)

When restoring contents (files, folder structures) from Trash, the same error happens, described below. Tested with content deleted from user profile doclib or from workspace doclib under default site.

For example:
* Open https://dmsservice.demo.sensenet.com/explore.html#/Root/Sites/Default_Site/workspaces/Document/losangelesdocumentworkspace/Document_Library
* Delete Aenean semper.doc
* Open Trash
* find Aenean semper.doc, run Restore action
* Content is restored, but the user gets the following error message:

An unexpected error occurred, please report the following technical details to your system
Exception type: System.NullReferenceException
Exception message:
Object reference not set to an instance of an object.

```txt
NullReferenceException: Object reference not set to an instance of an object.
   at SenseNet.Portal.UI.PortletFramework.ContextBoundPortlet.GetBindingRootPrivate() in E:\BuildAgent\_work\60\s\src\WebPages\PortletFramework\ContextBoundPortlet.cs:line 289
   at SenseNet.Portal.Portlets.BreadCrumbPortlet.GetBindingRoot() in E:\BuildAgent\_work\60\s\src\WebPages\Portlets\BreadCrumbPortlet.cs:line 191
   at SenseNet.Portal.UI.PortletFramework.ContextBoundPortlet.GetContextNodeInternal() in E:\BuildAgent\_work\60\s\src\WebPages\PortletFramework\ContextBoundPortlet.cs:line 189
   at SenseNet.Portal.UI.PortletFramework.ContextBoundPortlet.get_ContextNode() in E:\BuildAgent\_work\60\s\src\WebPages\PortletFramework\ContextBoundPortlet.cs:line 147
   at SenseNet.Portal.Portlets.BreadCrumbPortlet.GetBlacklist() in E:\BuildAgent\_work\60\s\src\WebPages\Portlets\BreadCrumbPortlet.cs:line 212
   at SenseNet.Portal.Portlets.BreadCrumbPortlet.GetParentsNodes() in E:\BuildAgent\_work\60\s\src\WebPages\Portlets\BreadCrumbPortlet.cs:line 216
   at SenseNet.Portal.Portlets.BreadCrumbPortlet.CreateChildControls() in E:\BuildAgent\_work\60\s\src\WebPages\Portlets\BreadCrumbPortlet.cs:line 299
```

---

@tusmester commented on [Thu Sep 27 2018](https://github.com/SenseNet/sensenet/issues/481#issuecomment-425153242)

Added stack trace to the description. ~This occurs only on the admin UI (Content Explorer), probably because there is no site context there.~ no, it does occur on the common UI too.

I think we should move this to the WebPages repo because it is about a portlet context.

**Comment by tusmester** [comment]
closed as obsolete
